### ISSUE TITLE
Warn if Protocol 1 is activated

### ISSUE THREAD

**Issue by Yamakaky** [arthepsy/ssh-audit#12]
I think it's depreciated?

**Comment by arthepsy** [comment]
It should be, but unfortunately it is still pretty widely used. One example is Cisco devices, e.g.:
![ssh-audit-ssh1](https://cloud.githubusercontent.com/assets/7356025/19449228/599ed800-94ad-11e6-8714-dc8ea025f9af.png)

**Comment by Yamakaky** [comment]
I said warn, not forbid ^^

**Comment by arthepsy** [comment]
Could You elaborate? I don't see that written anywhere.

**Comment by arthepsy** [comment]
SSH1 is rich of security vulnerabilities. It definitely should be "fail", not "warn".
