### ISSUE TITLE
Allow connection to a port other than 22

### ISSUE THREAD

**Issue by Yamakaky** [arthepsy/ssh-audit#17]

**Comment by arthepsy** [comment]
It's already supported. Please, read the **usage** section. 
Here's example how to specify port 1234:
`ssh-audit.py example.com:1234`

**Comment by Yamakaky** [comment]
I'm sorry, I tried `-p 2222` like in ssh.

**Comment by arthepsy** [comment]
No problem. Maybe that option could be added. Will think about it.

**Comment by Yamakaky** [comment]
Yeah, that would more intuitive. Maybe keeps the two options. Also, maybe read from `.ssh/config`?

**Comment by arthepsy** [comment]
I've added option `-p`/`--port` to specify port in 66b9e079a8b35f990df6a64f6be4d9924438fe9f. That's included in release 1.7.0.
